add runtime
aliyun/tea-csharp pull request #14
Opened 2019-10-18 08:19 UTC by liaoyustudent

2019-10-18 12:48 UTC, JacksonTian commented on Tea/TeaCore.cs
> +                throw new TeaRetryableException(e);
RetryableException 不是这样直接抛的。暂时抛个普通的异常就行。

2019-10-18 12:48 UTC, JacksonTian commented on Tea/TeaCore.cs
> +                throw new TeaRetryableException(e);
同上。

2019-10-18 12:49 UTC, JacksonTian requested changes
SMC

2019-10-21 02:24 UTC, AxiosCros commented on Tea/TeaUnretryableException.cs
> +            // TODO
这里为空，是要下一个 pr 补上吗

2019-10-21 02:27 UTC, JacksonTian approved these changes

2019-10-21 02:28 UTC, merged

2019-10-21 02:29 UTC, liaoyustudent commented on Tea/TeaUnretryableException.cs
> +            // TODO
这俩异常暂时没有实现的说明。