complete unit test
aliyun/tea-csharp pull request #22
Opened 2019-10-24 08:26 UTC by liaoyustudent

* 完善了部分单元测试
* 修改在测试过程中遇到的问题

2019-10-24 09:24 UTC, AxiosCros commented on TeaUnitTests/TeaCoreTest.cs
> +            teaRequest.Headers["host"] = "www.aliyun.com";
www.aliyun.com 改成 https://www.alibabacloud.com 试试

2019-10-24 09:33 UTC, AxiosCros commented on Tea/TeaCore.cs
> +            if(request.Method=="Post" && request.Body!=null)
确定 `ost` 是小写吗。不确定的话，这里的比较最好能忽略大小写的

2019-10-24 09:34 UTC, liaoyustudent commented on Tea/TeaCore.cs
> +            if(request.Method=="Post" && request.Body!=null)
应该是全大写，已修改

2019-10-25 02:12 UTC, AxiosCros commented on TeaUnitTests/TeaCoreTest.cs
> +            TeaCore.Sleep(1000);
这里要不要加个前后时间差的断言，证明确实过去了 1000 毫秒。

2019-10-25 02:13 UTC, AxiosCros commented on TeaUnitTests/TeaCoreTest.cs
> +            Assert.False(TeaCore.AllowRetry(dic, 3, _now));
这里的 dic 直接换成 null 就可以了，dic 的声明放到后面。

2019-10-25 02:14 UTC, JacksonTian commented on TeaUnitTests/TeaCoreTest.cs
> +            TeaCore.Sleep(1000);
没有断言的测试就不是测试

2019-10-25 02:14 UTC, JacksonTian commented on Tea/TeaModel.cs
> +                        if(mAddList!=null)
format

2019-10-25 02:14 UTC, JacksonTian requested changes
SMC

2019-10-25 02:51 UTC, JacksonTian approved these changes

2019-10-25 03:27 UTC, merged